import React from 'react';
import { Play, PlusCircle, Database, Cpu, Network, Zap, CheckCircle2, ArrowRight } from 'lucide-react';

const Home = ({ setActiveTab, onStartQuizWithId }) => {
  return (
    <div className="space-y-12 py-6">
      {/* Hero Section */}
      <div className="relative overflow-hidden rounded-3xl bg-gradient-to-b from-slate-900 via-slate-900/90 to-slate-950 border border-slate-800 p-8 sm:p-12 shadow-2xl">
        <div className="absolute top-0 right-0 -mt-12 -mr-12 w-96 h-96 bg-indigo-500/10 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute bottom-0 left-0 -mb-12 -ml-12 w-96 h-96 bg-violet-500/10 rounded-full blur-3xl pointer-events-none" />

        <div className="relative z-10 max-w-3xl space-y-6">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 text-xs font-semibold uppercase tracking-wider">
            <Zap className="w-3.5 h-3.5 text-indigo-400" />
            Powered by Spring Boot Microservices & React
          </div>

          <h1 className="text-4xl sm:text-5xl font-extrabold text-white tracking-tight leading-tight">
            Build, Manage & Master <br />
            <span className="bg-gradient-to-r from-indigo-400 via-violet-300 to-sky-400 bg-clip-text text-transparent">
              Interactive Microservice Quizzes
            </span>
          </h1>

          <p className="text-slate-400 text-lg sm:text-xl font-normal leading-relaxed">
            Create customized quizzes on demand, take tests in real-time, and manage a scalable question repository powered by Spring Cloud Eureka, API Gateway, and OpenFeign.
          </p>

          <div className="flex flex-wrap items-center gap-4 pt-4">
            <button
              onClick={() => setActiveTab('take-quiz')}
              className="flex items-center gap-2 px-6 py-3.5 rounded-xl bg-gradient-to-r from-indigo-600 to-violet-600 text-white font-semibold shadow-lg shadow-indigo-500/25 hover:shadow-indigo-500/40 hover:scale-[1.02] active:scale-[0.98] transition-all duration-150"
            >
              <Play className="w-5 h-5 fill-current" />
              Take a Quiz
            </button>

            <button
              onClick={() => setActiveTab('create-quiz')}
              className="flex items-center gap-2 px-6 py-3.5 rounded-xl bg-slate-800 hover:bg-slate-700/80 text-slate-200 border border-slate-700 font-semibold hover:scale-[1.02] active:scale-[0.98] transition-all duration-150"
            >
              <PlusCircle className="w-5 h-5 text-indigo-400" />
              Create New Quiz
            </button>

            <button
              onClick={() => setActiveTab('questions')}
              className="flex items-center gap-2 px-6 py-3.5 rounded-xl bg-slate-800/60 hover:bg-slate-800 text-slate-300 border border-slate-700/60 font-medium hover:scale-[1.02] active:scale-[0.98] transition-all duration-150"
            >
              <Database className="w-5 h-5 text-indigo-400" />
              Question Bank
            </button>
          </div>
        </div>
      </div>

      {/* Quick Action Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div 
          onClick={() => setActiveTab('take-quiz')}
          className="group relative p-6 rounded-2xl bg-slate-900/60 border border-slate-800 hover:border-indigo-500/50 hover:bg-slate-900/90 transition-all duration-200 cursor-pointer shadow-lg"
        >
          <div className="w-12 h-12 rounded-xl bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400 mb-4 group-hover:scale-110 transition-transform">
            <Play className="w-6 h-6" />
          </div>
          <h3 className="text-xl font-bold text-white mb-2 group-hover:text-indigo-400 transition-colors">
            Take a Quiz
          </h3>
          <p className="text-slate-400 text-sm leading-relaxed mb-4">
            Enter a Quiz ID generated by the system to attempt questions and see your instant score breakdown.
          </p>
          <div className="inline-flex items-center gap-1.5 text-xs font-semibold text-indigo-400 group-hover:translate-x-1 transition-transform">
            Start Quiz <ArrowRight className="w-4 h-4" />
          </div>
        </div>

        <div 
          onClick={() => setActiveTab('create-quiz')}
          className="group relative p-6 rounded-2xl bg-slate-900/60 border border-slate-800 hover:border-violet-500/50 hover:bg-slate-900/90 transition-all duration-200 cursor-pointer shadow-lg"
        >
          <div className="w-12 h-12 rounded-xl bg-violet-500/10 border border-violet-500/20 flex items-center justify-center text-violet-400 mb-4 group-hover:scale-110 transition-transform">
            <PlusCircle className="w-6 h-6" />
          </div>
          <h3 className="text-xl font-bold text-white mb-2 group-hover:text-violet-400 transition-colors">
            Generate Quiz
          </h3>
          <p className="text-slate-400 text-sm leading-relaxed mb-4">
            Select a subject category, specify the number of questions, and automatically build a custom quiz.
          </p>
          <div className="inline-flex items-center gap-1.5 text-xs font-semibold text-violet-400 group-hover:translate-x-1 transition-transform">
            Create Now <ArrowRight className="w-4 h-4" />
          </div>
        </div>

        <div 
          onClick={() => setActiveTab('questions')}
          className="group relative p-6 rounded-2xl bg-slate-900/60 border border-slate-800 hover:border-emerald-500/50 hover:bg-slate-900/90 transition-all duration-200 cursor-pointer shadow-lg"
        >
          <div className="w-12 h-12 rounded-xl bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center text-emerald-400 mb-4 group-hover:scale-110 transition-transform">
            <Database className="w-6 h-6" />
          </div>
          <h3 className="text-xl font-bold text-white mb-2 group-hover:text-emerald-400 transition-colors">
            Manage Questions
          </h3>
          <p className="text-slate-400 text-sm leading-relaxed mb-4">
            Add new questions, edit existing entries, filter by category, or clean up outdated items.
          </p>
          <div className="inline-flex items-center gap-1.5 text-xs font-semibold text-emerald-400 group-hover:translate-x-1 transition-transform">
            Open Bank <ArrowRight className="w-4 h-4" />
          </div>
        </div>
      </div>

      {/* Backend Microservices Architecture Overview */}
      <div className="p-8 rounded-2xl bg-slate-900/40 border border-slate-800 space-y-6">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h2 className="text-2xl font-bold text-white flex items-center gap-2">
              <Network className="w-6 h-6 text-indigo-400" />
              Microservices Architecture
            </h2>
            <p className="text-slate-400 text-sm mt-1">
              Decoupled services communicating via Eureka Server & OpenFeign
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <div className="p-4 rounded-xl bg-slate-950/80 border border-slate-800 space-y-2">
            <div className="text-xs font-bold text-indigo-400 uppercase tracking-wide">Gateway</div>
            <div className="text-lg font-semibold text-white">API-Gateway</div>
            <div className="text-xs text-slate-400">Port 8765</div>
            <p className="text-xs text-slate-500">Routes incoming requests to services with StripPrefix filter.</p>
          </div>

          <div className="p-4 rounded-xl bg-slate-950/80 border border-slate-800 space-y-2">
            <div className="text-xs font-bold text-violet-400 uppercase tracking-wide">Registry</div>
            <div className="text-lg font-semibold text-white">Eureka-Server</div>
            <div className="text-xs text-slate-400">Port 8761</div>
            <p className="text-xs text-slate-500">Service discovery for dynamic load balancing.</p>
          </div>

          <div className="p-4 rounded-xl bg-slate-950/80 border border-slate-800 space-y-2">
            <div className="text-xs font-bold text-emerald-400 uppercase tracking-wide">Microservice 1</div>
            <div className="text-lg font-semibold text-white">Question-Service</div>
            <div className="text-xs text-slate-400">Database & Questions CRUD</div>
            <p className="text-xs text-slate-500">Handles question generation, scoring, and question wrapping.</p>
          </div>

          <div className="p-4 rounded-xl bg-slate-950/80 border border-slate-800 space-y-2">
            <div className="text-xs font-bold text-sky-400 uppercase tracking-wide">Microservice 2</div>
            <div className="text-lg font-semibold text-white">Quiz-Service</div>
            <div className="text-xs text-slate-400">Quiz Orchestration</div>
            <p className="text-xs text-slate-500">Calls Question-Service via OpenFeign to build and score quizzes.</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
